# Generated by Django 4.1.2 on 2022-10-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='planed',
            new_name='planned',
        ),
    ]
