# Generated by Django 4.1.2 on 2022-10-27 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_category_user_bank_transaction_frombank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='cat',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
