# Generated by Django 4.1.2 on 2022-10-28 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0004_rename_category_transaction_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='actype',
            field=models.CharField(default='depository', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
