# Generated by Django 4.1.2 on 2022-10-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_bank_user_alter_transaction_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transid',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
