# Generated by Django 4.1.2 on 2022-10-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_transaction_transid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cat',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='budget.category'),
        ),
    ]
