# Generated by Django 4.1.2 on 2022-10-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_bank_bnkid'),
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unused', max_length=100)),
                ('cat', models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='budget.category')),
            ],
        ),
    ]
