# Generated by Django 4.1.2 on 2022-11-01 10:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0011_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='balanceCurrent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bank',
            name='lastUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='category',
            name='invest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='start',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fromCat',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromCat', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bnkid',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='key',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='planned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fromBank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.bank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transid',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
